<div class="wrap wp_dummy_content_generator-about-wrap">
	<h1>WP Dummy Content Generator <?=wp_dummy_content_generator_PLUGIN_NAME_VERSION?></h1>
	<div class="wp_dummy_content_generator-about-text">
		Thank you for choosing WP Dummy Content Generator! We hope that your experience with our plugin makes creating <b>Dummy users, Dummy posts & custom posts, Dummy woocommerce products</b> quick and easy.
	</div>
	<h2>What our plugin provides?</h2>
	<div class="wp_dummy_content_generator-about-integrations">
		<div class="wp_dummy_content_generator-feature feature-section col three-col">
			<div class="col wp_dummy_content_generator-col wp_dummy_content_generatorPanelWrapper">
				<div class="wp_dummy_content_generatorPanelHeading">Dummy Users</div>
				<div class="wp_dummy_content_generatorPanelBody">
					<p>As the name, "Dummy users" sounds like something illegal but actually its not. The main purpose of generating Dummy users is to check the functionality which is related to multiple users.</p>
					<p class="wp_dummy_content_generatorLinkWrapper">
						<a href="?page=wp_dummy_content_generator-users">Generate users</a>
					</p>
				</div>
			</div>
			<div class="col wp_dummy_content_generator-col wp_dummy_content_generatorPanelWrapper">
				<div class="wp_dummy_content_generatorPanelHeading">Dummy Posts/Custom Posts</div>
				<div class="wp_dummy_content_generatorPanelBody">
					<p>You can generate Dummy WordPress posts and custom posts. The purpose is again the same that it is for checking functionality like load more posts or filters etc.</p>
					<p class="wp_dummy_content_generatorLinkWrapper">
						<a href="?page=wp_dummy_content_generator-posts">Generate Posts</a>
					</p>
				</div>
			</div>
			<div class="col wp_dummy_content_generator-col wp_dummy_content_generatorPanelWrapper">
				<div class="wp_dummy_content_generatorPanelHeading">Woocommerce products</div>
				<div class="wp_dummy_content_generatorPanelBody">
					<p>Woocommerce dummy products are very important for e-commerce theme development. You can generate n number of woocommerce products using this plugin.</p>
					<p class="wp_dummy_content_generatorLinkWrapper">
						<a href="?page=wp_dummy_content_generator-products">Generate products</a>
					</p>
				</div>
			</div>
		</div>

	</div>

	<div class="wp_dummy_content_generator-extranotes">
		<h2>Worried about deleting data generated by WP Dummy Content Generator plugin?</h2>
		<div class="wp_dummy_content_generator-wdspromos-about">
			<p>Rest assured, the process of deleting the dummy data generated by our plugin is designed to be safe, reliable, and hassle-free. You can confidently remove all the generated content with ease and peace of mind. Our plugin ensures that the deletion process is handled smoothly, allowing you to maintain a clean and streamlined website whenever needed.</p>
			<p>
				<b>Enjoy the features of WP Dummy Content Generator!!!</b>
			</p>
		</div>		
	</div>
</div>